export enum Genre {
  ACTION = "ACTION",
  COMEDY = "COMEDY",
  DRAMA = "DRAMA",
  HORROR = "HORROR",
  ROMANCE = "ROMANCE",
  DOCUMENTARY = "DOCUMENTARY",
  ANIMATION = "ANIMATION",
  FANTASY = "FANTASY",
  SCI_FI = "SCI_FI",
}